# Generated by Django 4.0.3 on 2022-05-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=40, null=True, verbose_name='name'),
        ),
    ]
