# Generated by Django 4.0.3 on 2022-05-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
    ]
